# Generated by Django 5.0.6 on 2024-05-16 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='XXXXXXXXXXXXXXXx', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='XXXXXXXXXXXXXXXx', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='XXXXXXXXXXXXXXXx', max_length=100),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('postDate', models.TimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.category')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.location')),
            ],
        ),
        migrations.CreateModel(
            name='ApplayIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.user')),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.job')),
            ],
            options={
                'unique_together': {('userID', 'jobID')},
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.job')),
            ],
            options={
                'unique_together': {('name', 'jobID')},
            },
        ),
    ]
