# Generated by Django 5.0.6 on 2024-05-17 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_category_location_user_email_user_password_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='postDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
