# Generated by Django 5.0.6 on 2024-05-17 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_alter_job_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
